backend:
  name: git-gateway
  branch: cms # Branch to update (optional; defaults to master)
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/static/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
        - name: "post"
          label: "Bericht"
          folder: "content/post"
          create: true
          slug: "{{slug}}"
          fields:
                - {label: "Titel", name: "title", widget: "string"}
                - {label: "Veröffebtlichungsdatu", name: "date", widget: "datetime"}
                - {label: "Inhalt", name: "body", widget: "markdown"}
